language: java


jdk:
  - oraclejdk8

before_script: 
- cd chrome_extension/
- bash updateCleanVersion.sh --emulation-mode


env:
    global:
    - SAUCE_USERNAME: "mooltipass"
    - secure: "DM7jC+cyseBqdOFm7wmidAYUy5swauFONLASUBUKMH6qbupnnFDnjv/DWAzG0Zd282zKNiOXA9XL1CW02VAahliy8p3P/y8avQJmERpIjsUUMgmzEudKQD/i+cQIS0yWYa1UMlSJBhHvoIRKr+O22l08CV3nCe0JhaQsIKmPSJ+5nTSbEkYbkDrvGLpIvkqNNrfps5g2kgzlw97b/r7mKUb55o2GrCpFP0xmNCyllHqBffDE7G+DfqAt/TLNFPvNNRS1VoObsw33W28ZeHhzKXZgDqArzvsS8dhEBUpvS77Q/xxM3CdVipTtVA2QX8LnfTfoEsnqek1sRiAELaiHGDlmeZr9LIskOKCyTHC8U9siqD7ND9PdTtLOkaoOwC/TVkYgLKff05Et8c3ehkVne63ayylwTvE59kTFPypU8z+fJ55ubmBXcpBM7sCGBcuVVyG+Sfn6hnNeELGL40Yyrjy9BF8u8Cb1MKBlElqHVpE08vYOXoLS8BZlQzNoFvkZeJ8BR/kqJD5YCw4BflsRwuv1pqwzOD5gnKerUUGEGPLEgIf0pho8wSu1hjDbw5CQC3V6Mc8N+Bs23YawRZ2xcX1g2xPziz4+2DJO4/pjvmFYCM3QExBrafNsz3uGche3JZqnsymBgpIxCWRyNs5FLhplD8+gUoZx7UQ8uAf6Wk0="
    - secure: "eaD9sYD5r6LOwrp9wgF5yZHldJYiU30xeY1uKJuZ5cqFU1r0GSC2zoLBo4muISIoRuvnQk39eNs15YK/0o96ztK8bWglO6iBW8unBTT3v0RXYg1bRLlxZtABVCImpQaNzUSMrxXZ7VHC6+nQe8aRw40EB9gO7QDgrPdgLJWUi744lYhPOrNETdFroBvADw8Nu3BPUxyoy+sQwSiJuha2UYWLXCIIpMG9BNeQla5p2e4B9Kyta9dlxsaeMk/s4BJPR/kKRvsdUtDDxmGAqICj42rtZk9qZEyD3GvAk+/yHe+7nIXsnwV19zmwPGF0Y386GpyIGZbYywvXULyg5LRwjfou2Y1m4AaCAV612nQTcyPxUradsqz/0iHFDWK54stcegtlxvwklb4e3n1iGIOUude0zcOxGHL3aUy9WMHBzIR8MDx+8/JLy6n69d6qaxNyRUQNs9R+5JrvqUgX8IzaqjjylvnM4S5KquLB6Z9IjqsQH4obKfkftTAnDV9+WuPdjivcqPGutdUmjMMNc02qtcMK3T2SjT19lF1V+P1g5Kc6/CFRkOW0H5MpfN+Su14V/sidp6l8TzlD9x4Y558TeGYmVi4l5uKMRIqeIwLMjBqZvQAvrJYmVmd41lEATWLZAYqEj/ru5xoNOAHYeRJi8NOzmvviXtGtlQQIPmdf2ZE="
script:
- mv mooltipass-extension.zip ./../sauce_labs_tests/chrome_extension.crx
- cd ./../sauce_labs_tests
- mvn install -B 
