language: java
sudo: enabled
addons:
  apt:
    packages:
      - libgnome-keyring-dev
      - icnsutils
      - graphicsmagick
      - xz-utils
      - libusb-1.0-0
      - libusb-1.0-0-dev
      - libudev-dev
      - gcc-multilib
      - g++-multilib
jdk:
  - oraclejdk8
before_script: cd chrome_extension

env:
    global:
    - secure: "Sig6uRBI4E3YJ4TZM0UiE5u1dcoDDA/sYJyzoDhBS5Bo31oZDgUSJbnMxXPAXCpzfRZeDzLi+KDw3xjasZ6v1+aIZPami7p0WcpmMYJ1NgNC47yQ1a4uSElQB7FLet6NJi3Q5R1L4EGcc2T7nw1M3TS34plCDpR+IOH7kXL+E6RbHQWvHkZhbhCmg4mBmPY4FTBZyTKWUtqKmmDq3GDadsitrGggLB3sera60dp/f1N9RiwzyIByzvUPLZHvmitSffXo1u0e9JbR5xU36m4o1Tu8LCBgmF20tPASyP+ZSxGOeOF8IVewNoC0Fsm9Eoi9PLK+MUun2lYnyssl30qK3GUysuVgJmdt6tPuYOMK31sxdPTQ8cWJ56hNd31BrmS+bYZh8ZkA87hrhCHIYrzatDbWisF61uVmr5U/sVMJXArfwrRT76kf4kg7xLwz7I5UTg5GpXuGKSLmddgUTs1+jytVsd5+btm350tursgMX6Rfua8ZNR1drpcs/55VyppLAQQ1eF/Om28yiJ4VZAWNbVMQn4fTBYzbopq6vtQl9+KeZWfx55pCoaN1l9jDsP96Sgf6E5lLMc4AY2GVhV9a8FE9LiXs3PzZKXk0RmTZjM6AXbHEqVRWZzgTQS/WqpTwHCEv1XYGQb227gsgyD4JLFdK8B89GTouia5KuR+ZKsg="
    - secure: "Ol3PBuPiaqAwfNXzSs7j7FwX0dN7hpMkwbGEtLa/Jth1ogsRfpVX8JHcIQ1Iwg1vJBmLUK+8X4l+syRekMzErSz/ri+TKlY5NtNpH9I1lcSLt2H91m1bHT2axynTS+AjVI//WunaPluNJYy0PLu294y5S2IzzMUeuoZlwBnXp1RyGhXWJR56Na6ms2dybYjPqfQljzRD3onte8DSareJLOHM/H1f+q7W9t+vYtNLwXsJ2nTrs49+iicunjflNMh1T8aTXPkju8d6TMJ4DVBJy9QIa3/iMSyecp9Qu2zRawetnjmPROH5rHn6F5uIlUrR+HPeWJPabXe2siBMvhULFBZIz5I2MYiSij60npqM2kp9We8Vx4JzlPu2sXLaVlbmZv+bj6Mw4fh41wKJ6cUEkyGaIMR3FVBZeRKYQDhK7WBXnGZeW+oPXxLUxqYFrU3cf/1ackEdbdPlwMnVkKaqLSQILNbtLlwx0F9EdO+yJY31pMfz1jE9YTPFLwCsU6NH8ZGgTeuQJmPIuczip1s5jeQcGjXi3byPdZENSXC+MBUg98SdiBLGC455LFXHI6yBaqi4QbxIiRjX8gDu5wsP/ctbLOMgfpcFGRhrou+G1TqWy90KH2jGKqCvQJvvv299Czqx0DzVjVy2ppohBBZ1NPGiOklxxwztKtpCCyl01PI="
script:
- updateCleanVersion.sh
- cd ./../sauce_labs_tests
- mvn install -B 
